import { createOpenAPI } from "fumadocs-openapi/server";

// The spec is generated by the Go API via `make gen-openapi` (go/api/openapi.json).
export const openapi = createOpenAPI({
  input: ["../../../../go/api/openapi.json"],
});
