import { createOpenAPI } from "fumadocs-openapi/server";

// The spec is generated by the Go API via `make gen-openapi` (go/api/openapi.json).
// It is copied here so the Docker build context (ts/) can reach it.
// After running `make gen-openapi`, copy go/api/openapi.json to this file.
export const openapi = createOpenAPI({
  input: ["./openapi/openapi.json"],
});
